#!/bin/sh
# vim: set ft=sh

set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)
cat > $payload <&0

access_token=$(jq -r '.source.access_token // ""' < $payload)
username=$(jq -r '.source.username // ""' < $payload)
box=$(jq -r '.source.box // ""' < $payload)
provider=$(jq -r '.source.provider // ""' < $payload)
number=$(jq -r '.version.number' < $payload)

abort() {
  echo "$@"
  exit 1
}

[ -n "$access_token" ] || abort "missing access_token"
[ -n "$username" ] || abort "missing username"
[ -n "$box" ] || abort "missing box"
[ -n "$provider" ] || abort "missing provider"

curl -f -s -X GET https://vagrantcloud.com/api/v1/box/${username}/${box} \
  -d "access_token=${access_token}" > box.json

provider_name=$(echo $provider | jq -R .)

lower_bound="$number"
range=""
if [ "$number" = "null" ]; then
  lower_bound="0"
  range="[length-1:]" # workaround [-1] not working
fi

# buckle up
#
# NB: sort_by claims to be deprecated, but sort(.number) doesn't seem to
# actually work, which is what the docs recommend
jq -r "
  .versions | sort_by(.number) |
    map(
      select(
        .status == \"active\" and
        .number > ${lower_bound} and
        (.providers | map(.name) | contains([$provider_name]))
      )
    ) | .$range | map({number: .number})
" < box.json >&3
